name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:latest

    steps:

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - run: N64_GCCPREFIX=/n64_toolchain ./buildall.sh

    - name: Upload benchmark3d_f3dex2.z64
      uses: actions/upload-artifact@v7
      with:
        name: benchmark3d_f3dex2.z64
        path: f3dex2/benchmark3d_f3dex2.z64
